name: ML CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_training:
        description: 'Run Model Training'
        required: false
        default: "true"

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}/churn-classifier
  PYTHON-VERSION: '3.10'

jobs:
  # ==========================================
  # Job 1: Code Quality & Linting
  # ==========================================
  lint:
    name: Code Quality Check
    runs-on: ubuntu-lastest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON-VERSION }}
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}--pip-lint-${{ hasFile( 'requirements-dev.txt' ) }}
          restore-keys: |
            ${{ runner.os }}-pip-lint-
            ${{ runner.os }}-pip-
      
      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black flake8
      
      - name: Run ruff
        run: |
          ruff check src/ tests/ --output-format=github
        continue-on-error: false
      
      - name: Run Black 
        run: |
          black --check src/ tests/ --line-length=100
        continue-on-error: true
      
      - name: Run flake8
        run: |
          flake8 src/ tests/ --max-line-length=100 --statistics
        continue-on-error: true

  # ==========================================
  # Job 2: Unit Testing
  # ==========================================
  test: 
    name: Unit test
    runs-on: ubuntu-latest
    needs: lint

    strategy:
       matrix: 
        python-version: [ '3.9', '3.10', '3.11' ]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hasFile('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      
      - name: Generate sample data for tests
        run: |
          python -c "from src.utils import setup_directories, generate_sample_data; setup_directories(); generate_sample_data('data/raw/churn_data.csv', n_samples=500)"
      
      - name: Run pytest with coverage
        run: |
          pytest tests/ -v \
            --cov=src \
            --cov-report=xml \
            --cov-report=term-missing \
            --cov-report=html
      
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittest
          name: codecov-${{ matrix.python-version }}
          fail_ci_if_error: false
      
      - name: Upload coverage HTML
        uses: actions/upload-artifact@v3
        if: matrix.python-version == '3.10'
        with:
          name: coverage-html
          path: htmlcov/

  dvc-pipeline-inside-container:
    name: DVC Pipeline (Inside Container)
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install DVC
        run: |
          pip install dvc[s3]
      
      - name: Configure DVC remote (if using S3)
        if: secrets.AWS_ACCESS_KEY_ID != ''
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          dvc remote modify myremote access_key_id $AWS_ACCESS_KEY_ID
          dvc remote modify myremote secret_access_key $AWS_SECRET_ACCESS_KEY

      - name: Pull DVC data
        run: |
          dvc pull || echo "No remote data to pull"
        continue-on-error: true

      - name: Build Docker Image 
        run: |
          docker build -t ml-pipeline:latest -f docker/Dockerfile .
      
      - name: Run DVC pipeline in container 
        run: |
          docker run --rm \
          -v $(pwd)/data:/app/data \
          -v $(pwd)/models:/app/models \
          -v $(pwd)/params.yml:/app/params.yml \
          -v $(pwd)/metrics.json:/app/metrics.json \
          -w /app \
          ml-pipeline:latest \
          bash -c "
            python -c 'from src.utils import setup_directories, generate_sample_data; setup_directories(); generate_sample_data(\"data/raw/churn_data.csv\", n_samples=1000)' &&
          "
      
      - name: Display metrics
        run: |
          if [ -f metrics.json ]; then
            echo "Model metrics:"
            cat metrics.json | python -m json.tool
          fi
      
      - name: Push DVC data
        run: |
          dvc push || echo "Could not push to remote"
        continue-on-error: true
      
      - name: Upload pipeline artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pipeline-outputs
          path: |
            models/*.pkl
            metrics.json
            plots/
          retention-days: 30
  
  # ==========================================
  # Job 4: Docker Build & Push
  # ==========================================
  docker-build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: [test]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        if: secrets.DOCKER_USERNAME != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract Metadata
        id: meta 
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: |
            type=ref, event=branch
            type=sha, prefix={{branch}}-
            type=raw, value=latest, enable={{is_default_branch}}
      
      - name: Build and Push Production Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: ${{ secrets.DOCKER_USERNAME != '' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry, ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry, ref=${{ env.DOCKER_IMAGE}}:buildcache, mode=max
      
      - name: Build Development Image
        uses: docker/build-push-action@v5
        with: 
          context: .
          file: ./docker/Dockerfile.dev
          push: ${{ secrets.DOCKER_USERNAME != '' }}
          tags: ${{ env.DOCKER_IMAGE }}:dev
          cache-from: type=registry, ref=${{ env.DOCKER_IMAGE }}:dev-buildcache
          cache-to: type=registry, ref=${{ env.DOCKER_IMAGE }}:dev-buildcache, mode=max
      
      - name: Image digest
        run: echo ${{ steps.meta.outputs.digest }}

  integration-test:
    name: Integration Test 
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      
      - name: Login to docker hub 
        if: secrets.DOCKER_USERNAME != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: pull latest image 
        run: |
          docker pull ${{ env.DOCKER_IMAGE }}:latest || docker build -t ${{ env.DOCKER_IMAGE }}:latest -f docker/Dockerfile .

      - name: Test preprocessing
        run: |
          docker run --rm \
            -v $(pwd)/data:/app/data \
            -v $(pwd)/params.yml:/app/params.yml \
            ${{ env.DOCKER_IMAGE }}:latest \
            bash -c "python -c 'from src.utils import setup_directories, generate_sample_data; setup_directories(); generate_sample_data(\"data/raw/churn_data.csv\", n_samples=100)' && python -m src.preprocess"
      
      - name: Test Training
        run: |
          docker run --rm \
            -v $(pwd)/data:/app/data \
            -v $(pwd)/models:/app/models \
            -v $(pwd)/params.yml:/app/params.yml \
            ${{ env.DOCKER_IMAGE }}:latest \
            python -m src.train
      
      - name: Test evaluation
        run: |
          docker run --rm \
            -v $(pwd)/data:/app/data \
            -v $(pwd)/models:/app/models \
            -v $(pwd)/params.yml:/app/params.yml \
            -v $(pwd)/metrics.json:/app/metrics.json \
            ${{ env.DOCKER_IMAGE }}:latest \
            python -m src.evaluate
      
      - name: Verify outputs
        run: |
          if [ -f models/churn_model.pkl ]; then
            echo "Model file created successfully"
          else
            echo "Model file not found"
            exit 1
          fi

          if [ -f metrics.json ]; then
            echo "Metrics file created successfully"
            cat metrics.json
          else  
            echo "Metrics file not found"
            exit 1
          fi

  status-check:
    name: pipeline status
    runs-on: ubuntu-latest
    needs: [lint, test, docker-build, integration-test]
    if: always()



        


  
      